name: run-script

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: run the script
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run script 
        run: bash k8s-dotfiles.sh

      # - name: source bashrc file
      #   run: source ~/.bashrc
      
      - name: run kubectx 
        run: source ~/.bashrc && command -v kubectx